### ISSUE TITLE
Incremental/Streaming calculation of indicators

### ISSUE THREAD

**Issue by gmosx** [TulipCharts/tulipnode#1]
It would be useful to support streaming/incremental calculation of indicators (e.g. in a real-time charting scenario). AFAICS the current interface doesn't support this. Any plans to add this functionality in the future?

**Comment by codeplea** [comment]
No, there are currently no plans to add that. I think it would add a ton of complexity to store state in-between calls.

To continue an indicator, you usually only need to go a few bars back. Most of these indicators can process hundreds of millions of bars a second [1]. So I think it is very usable in a real-time applications. You just waste a few CPU cycles and recalculate the last few hundred bars.

I guess adding a javascript object that stores state and recalculates as needed wouldn't be too much work.

[1] [Tulip Indicators benchmark](https://tulipindicators.org/benchmark)
