### ISSUE TITLE
MOM and Invalid number of inputs.

### ISSUE THREAD

**Issue by bortch** [TulipCharts/tulipnode#12]
Hello,

Here: Node v8.4.0 & tulipnode 0.8.1 on Ubuntu 16.04.2 LTS

I can't figure out what's wrong. 
I'm stuck with the following error:

`.../TulipTest/node_modules/tulind/index.js:17
      return tulind.callbyindex(index, inputs, options, callback);`

`TypeError: Invalid number of inputs.`
 `   at Object.indicator (.../TulipTest/node_modules/tulind/index.js:17:21)`
 `   at Object.<anonymous> (.../TulipTest/test/MOM.js:10:17)`
 `   at Module._compile (module.js:573:30)`
 `   at Object.Module._extensions..js (module.js:584:10)`
 `   at Module.load (module.js:507:32)`
 `   at tryModuleLoad (module.js:470:12)`
 `   at Function.Module._load (module.js:462:3)`
 `   at Function.Module.runMain (module.js:609:10)`
 `   at startup (bootstrap_node.js:158:16)`
 `   at bootstrap_node.js:598:3`

My test file MOM.js contains:

`const mom = require('tulind').indicators.mom `

`function callback (e,r) {
   console.log(r)
 }`

`const real = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`
`const period = [1]`

`console.log(mom.indicator(real, period, callback))`

Thanks

**Comment by codeplea** [comment]
Try `mom.indicator([real], period, callback)`

It expects inputs to be arrays of arrays for consistency.

**Comment by bortch** [comment]
Sorry my bad.
 
Thank you for pointing it out!
