### ISSUE TITLE
For termux android

### ISSUE THREAD

**Issue by cristeamihai** [TulipCharts/tulipnode#13]
I can not install tulind on termux android
I have already latest nodejs, npm

**Comment by cristeamihai** [comment]
I had a pics of all error. Give email so i can send to you. Thank yoy

**Comment by cristeamihai** [comment]
! tulind@0.8.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tulind@0.8.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tulind package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tulind
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tulind
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/data/com.termux/files/home/.node-red/npm-debug.log

**Comment by cristeamihai** [comment]
Thank you anyway for great work you did. Currently i use technicalindicators , but i need psar  from tulind. It ll be great thing to make it work on termux, or in the future can you provide a node or flow for node- red. Thank you again

**Comment by codeplea** [comment]
I'm not familiar with termux. Do you have a C++ compiler installed for it?

**Comment by cristeamihai** [comment]
Who are you?

În 28 noiembrie 2017 18:55:33 EET, Lewis Van Winkle <notifications@github.com> a scris:
>I'm not familiar with termux. Do you have a C++ compiler installed for
>it?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/TulipCharts/tulipnode/issues/13#issuecomment-347589110

-- 
Trimis de pe dispozitiv Android cu K-9 Mail. Rog scuzati mesajul scurt.
