### ISSUE TITLE
Failure to install on osx

### ISSUE THREAD

**Issue by tSchubes** [TulipCharts/tulipnode#14]
Receiving a 404 for tulind binaries when attempting to npm i tulind

```
npm i tulind

> tulind@0.8.7 install /Volumes/foo/bar
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.7/Release/tulind-v0.8.7-node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for tulind@0.8.7 and node@8.8.1 (node-v57 ABI, unknown) (falling back to source compile with node-gyp) 
```

**Response headers:**
```
Content-Type: application/xml
Date: Tue, 28 Nov 2017 13:09:41 GMT
Server: AmazonS3
Transfer-Encoding: chunked
x-amz-id-2: SiGKbhIF8k+b6VqAGclquRm0qGdN7/EX+UQKmAOl5d1X9D5YrFKkp+ezlKKj8qFI3UjYZOJd5qQ=
x-amz-request-id: 782E6E6D1CCEAA50
```

**Body:**
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>NoSuchKey</Code>
    <Message>The specified key does not exist.</Message>
    <Key>tulind/v0.8.7/Release/tulind-v0.8.7-node-v57-darwin-x64.tar.gz</Key>
    <RequestId>782E6E6D1CCEAA50</RequestId>
    <HostId>SiGKbhIF8k+b6VqAGclquRm0qGdN7/EX+UQKmAOl5d1X9D5YrFKkp+ezlKKj8qFI3UjYZOJd5qQ=</HostId>
</Error>
```

**Comment by tSchubes** [comment]
Initially a duplicate of #5 my apologies. Re-named to cover new issue of using `--build-from-source` yielding failures.
I'm using a folder path which contains spaces and am not terribly keen on creating a new workspace just for this project.

```
SOLINK_MODULE(target) /Volumes/Storage/foo bar/node_modules/tulind/lib/binding/Release/node-v57-darwin-x64/tulind.node
clang: error: no such file or directory: 'bar/node_modules/tulind/lib/binding/Release/node-v57-darwin-x64/tulind.node'
make: *** [/Volumes/Storage/foo bar/node_modules/tulind/lib/binding/Release/node-v57-darwin-x64/tulind.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 17.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Volumes/Storage/foo bar/node_modules/tulind/lib/binding/Release/node-v57-darwin-x64/tulind.node" "--module_name=tulind" "--module_path=/Volumes/Storage/foo bar/node_modules/tulind/lib/binding/Release/node-v57-darwin-x64"
gyp ERR! cwd /Volumes/Storage/foo bar/node_modules/tulind
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Volumes/Storage/foo bar/node_modules/tulind/lib/binding/Release/node-v57-darwin-x64/tulind.node --module_name=tulind --module_path=/Volumes/Storage/foo bar/node_modules/tulind/lib/binding/Release/node-v57-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Volumes/Storage/foo bar/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 17.0.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Volumes/Storage/foo bar/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Volumes/Storage/foo bar/node_modules/tulind
node-pre-gyp ERR! node -v v8.8.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Volumes/Storage/foo bar/node_modules/tulind/lib/binding/Release/node-v57-darwin-x64/tulind.node --module_name=tulind --module_path=/Volumes/Storage/foo bar/node_modules/tulind/lib/binding/Release/node-v57-darwin-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tulind@0.8.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tulind@0.8.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tim/.npm/_logs/2017-11-28T13_18_28_379Z-debug.log
```

**Comment by codeplea** [comment]
Can you try it without a space in your path and report back if it works? If it does I would think you could just copy the files over.

I'm not sure exactly where the bug is coming from. I don't have access to an OSX machine right now, and the spaces in path is not an issue on Windows.

**Comment by CapCap** [comment]
Having same issue, path has no spaces

**Comment by franciskim** [comment]
Same issues here. Also, the following link is a 404:

https://tulipnode.s3.amazonaws.com/tulind/v0.8.7/Release/tulind-v0.8.7-node-v48-darwin-x64.tar.gz

**Comment by codeplea** [comment]
The 404 is normal, it should fall-back to building from sources.

I did update a couple things. Could you try again and let me know if the problems persist?

**Comment by jcfinnerup** [comment]
I have the same problem as well as of today

**Comment by jcfinnerup** [comment]
Okay i managed to fix it for me. 
I took a look at what endpoints were available for download instead of the autogenerated link by tulips `package.json`. 

I downloaded the library from Github, put it locally into a folder in the project, and installed it from there using ```npm install <path>```

Before doing that i changed the the value of the binary package_name in tulips package.json to the latest URL i could find that worked: 

```
"binary": {
        "module_name": "tulind",
        "module_path" : "./lib/binding/{configuration}/{node_abi}-{platform}-{arch}/",
        "remote_path" : "./{module_name}/v{version}/{configuration}/",
        "package_name": "tulind-v0.8.9-node-v59-win32-x64.tar.gz",
        "host": "https://tulipnode.s3.amazonaws.com"
    }
```
Exchanged the package_name with:
` tulind-v0.8.9-node-v59-win32-x64.tar.gz `. 

Now it works

**Comment by codeplea** [comment]
@jcfinnerup You're saying that downloading a Win32 binary let you run it on OSX? That doesn't make sense.

**Comment by Neewd** [comment]
Still got the problem ... 

And here is my full stack trace : `MacBook-Pro-de-Clement:_logs clementbacouelle$ npm install tulind

> tulind@0.8.9 install /Users/clementbacouelle/node_modules/tulind
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.9/Release/tulind-v0.8.9-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for tulind@0.8.9 and node@8.4.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/clementbacouelle/node_modules/tulind/lib/binding/Release/node-v57-darwin-x64/tulind.node" "--module_name=tulind" "--module_path=/Users/clementbacouelle/node_modules/tulind/lib/binding/Release/node-v57-darwin-x64"
gyp ERR! cwd /Users/clementbacouelle/node_modules/tulind
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/clementbacouelle/node_modules/tulind/lib/binding/Release/node-v57-darwin-x64/tulind.node --module_name=tulind --module_path=/Users/clementbacouelle/node_modules/tulind/lib/binding/Release/node-v57-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/clementbacouelle/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 17.3.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/clementbacouelle/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/clementbacouelle/node_modules/tulind
node-pre-gyp ERR! node -v v8.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/clementbacouelle/node_modules/tulind/lib/binding/Release/node-v57-darwin-x64/tulind.node --module_name=tulind --module_path=/Users/clementbacouelle/node_modules/tulind/lib/binding/Release/node-v57-darwin-x64' (1)
npm WARN enoent ENOENT: no such file or directory, open '/Users/clementbacouelle/package.json'
npm WARN clementbacouelle No description
npm WARN clementbacouelle No repository field.
npm WARN clementbacouelle No README data
npm WARN clementbacouelle No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tulind@0.8.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tulind@0.8.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/clementbacouelle/.npm/_logs/2017-12-25T20_11_18_375Z-debug.log`

**Comment by tSchubes** [comment]
@codeplea I was able to install successfully in a folder without spaces in the path name however doing this then moving my project to the desired path is not a viable solution as the same error re-occurs every time I install a new npm module or update my modules from inside the new path.

Additionally, it's all good and well for individual devs to do such a workaround on their pet projects but I wouldn't be game to force a full team of devs to perform such a workaround. The consensus would be to use a different module.

**Comment by HaveThee93mil** [comment]
Did not work for me.

**Comment by codeplea** [comment]
The spaces in path issue appears to be caused by a problem with [node-pre-gyp](https://github.com/mapbox/node-pre-gyp). I've opened an issue with them. Please continue the discussion of this issue here: https://github.com/TulipCharts/tulipnode/issues/39

Hopefully we will have a fix soon.
