### ISSUE TITLE
Windows 10 tulind installation - v57 doesn't exist and "npm install tulind" fails

### ISSUE THREAD

**Issue by flamewheel** [TulipCharts/tulipnode#15]
Hi there,

Apologies if I'm missing details - not very proficient with coding in general. I'm attempting to install tulind locally on Windows 10 with nodejs version 8.9.1, and "npm install tulind" runs into an error where it's attempting to pull tulind-v0.8.7-node-v57-win32-x64.tar.gz from the aws site, but that file doesn't exist. When I go and look at https://tulipnode.s3.amazonaws.com/, I see the latest win32-x64 version on there is v51.

Can provide more details if you tell me what I need to provide! I've included the debug log for the run as well as the cmd.exe output.

[tulind_install_failure_w10_20171203_220900.log](https://github.com/TulipCharts/tulipnode/files/1525564/tulind_install_failure_w10_20171203_220900.log)

[2017-12-04T03_06_00_770Z-debug.log](https://github.com/TulipCharts/tulipnode/files/1525553/2017-12-04T03_06_00_770Z-debug.log)

**Comment by codeplea** [comment]
I haven't published binaries for node 8 yet. I'll try to get them out in the next couple days.

**Comment by athaax** [comment]
^ that would be wonderful :D

**Comment by codeplea** [comment]
Binaries for node 8 and 9 on Windows are now published for the latest version. Please give it a try and let me know how it works.

**Comment by flamewheel** [comment]
v57 downloaded. Going to play around with the bot now. Thanks!
