### ISSUE TITLE
Failure during npm install

### ISSUE THREAD

**Issue by gerosyab** [TulipCharts/tulipnode#16]
Hello, I'm having trouble with npm installing in CentOS 6. (npm : 5.5.1, node : 6.12.1)

I thought it was about some compiling error.

Here is my logs, could you please give me some advice?

> 
> tulind@0.8.7 install /home/gekko/gekko/node_modules/tulind
> node-pre-gyp install --fallback-to-build

make: Entering directory `/home/gekko/gekko/node_modules/tulind/build'
  CXX(target) Release/obj.target/tulind/tulind.o
In file included from ../tulind.cpp:25:
../../nan/nan.h:45:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /home/gekko/.node-gyp/6.12.1/include/node/node.h:42,
                 from ../../nan/nan.h:49,
                 from ../tulind.cpp:25:
/home/gekko/.node-gyp/6.12.1/include/node/v8.h:345: error: expected unqualified-id before ‘using’
/home/gekko/.node-gyp/6.12.1/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/home/gekko/.node-gyp/6.12.1/include/node/v8.h:362: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/home/gekko/.node-gyp/6.12.1/include/node/v8.h:369: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/home/gekko/.node-gyp/6.12.1/include/node/v8.h:373: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.1/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/home/gekko/.node-gyp/6.12.1/include/node/v8.h:441: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.1/include/node/v8.h: At global scope:
/home/gekko/.node-gyp/6.12.1/include/node/v8.h:481: error: expected unqualified-id before ‘using’
/home/gekko/.node-gyp/6.12.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/home/gekko/.node-gyp/6.12.1/include/node/v8.h:820: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/home/gekko/.node-gyp/6.12.1/include/node/v8.h:845: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.1/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/home/gekko/.node-gyp/6.12.1/include/node/v8.h:857: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.1/include/node/v8.h: At global scope:
/home/gekko/.node-gyp/6.12.1/include/node/v8.h:882: error: expected unqualified-id before ‘using’
/home/gekko/.node-gyp/6.12.1/include/node/v8.h:1119: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.1/include/node/v8.h:1125: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.1/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/home/gekko/.node-gyp/6.12.1/include/node/v8.h:3279: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.1/include/node/v8.h: At global scope:
/home/gekko/.node-gyp/6.12.1/include/node/v8.h:4499: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.1/include/node/v8.h:4515: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.1/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/home/gekko/.node-gyp/6.12.1/include/node/v8.h:7544: error: ‘nullptr’ was not declared in this scope
In file included from ../../nan/nan.h:192,
                 from ../tulind.cpp:25:
../../nan/nan_maybe_43_inl.h: At global scope:
../../nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:19: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:24: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:29: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:37: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:45: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:52: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:60: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:71: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:79: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:87: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:96: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:105: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:115: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:125: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:141: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:149: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:155: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:164: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:171: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:179: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:186: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:194: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:202: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:210: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:218: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:226: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:234: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:244: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:254: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:266: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:277: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:284: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:290: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:296: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:302: error: expected initializer before ‘<’ token
../tulind.cpp:316: error: expected ‘}’ at end of input
../../nan/nan_callbacks_12_inl.h:167: warning: ‘void Nan::imp::FunctionCallbackWrapper(const v8::FunctionCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:181: warning: ‘void Nan::imp::GetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:197: warning: ‘void Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:253: warning: ‘void Nan::imp::PropertyGetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:270: warning: ‘void Nan::imp::PropertySetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:290: warning: ‘void Nan::imp::PropertyEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:306: warning: ‘void Nan::imp::PropertyDeleterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:323: warning: ‘void Nan::imp::PropertyQueryCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:428: warning: ‘void Nan::imp::IndexGetterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:444: warning: ‘void Nan::imp::IndexSetterCallbackWrapper(uint32_t, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:464: warning: ‘void Nan::imp::IndexEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:480: warning: ‘void Nan::imp::IndexDeleterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:496: warning: ‘void Nan::imp::IndexQueryCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
make: *** [Release/obj.target/tulind/tulind.o] 오류 1
make: Leaving directory `/home/gekko/gekko/node_modules/tulind/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 2.6.32-431.5.1.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/gekko/gekko/node_modules/tulind/lib/binding/Release/node-v48-linux-x64/tulind.node" "--module_name=tulind" "--module_path=/home/gekko/gekko/node_modules/tulind/lib/binding/Release/node-v48-linux-x64"
gyp ERR! cwd /home/gekko/gekko/node_modules/tulind
gyp ERR! node -v v6.12.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/gekko/gekko/node_modules/tulind/lib/binding/Release/node-v48-linux-x64/tulind.node --module_name=tulind --module_path=/home/gekko/gekko/node_modules/tulind/lib/binding/Release/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/gekko/gekko/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Linux 2.6.32-431.5.1.el6.x86_64
node-pre-gyp ERR! command "/usr/bin/node" "/home/gekko/gekko/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/gekko/gekko/node_modules/tulind
node-pre-gyp ERR! node -v v6.12.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/gekko/gekko/node_modules/tulind/lib/binding/Release/node-v48-linux-x64/tulind.node --module_name=tulind --module_path=/home/gekko/gekko/node_modules/tulind/lib/binding/Release/node-v48-linux-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tulind@0.8.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tulind@0.8.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gekko/.npm/_logs/2017-12-07T05_19_17_209Z-debug.log
>

**Comment by codeplea** [comment]
I did a couple updates. Could you try again and let me know if it works?

**Comment by gerosyab** [comment]
I tried to npm install tulind and got similar log messages as before
(Only differnence with previous situation is node version : 6.12.1 -> 6.12.2)

> tulind@0.8.9 install /home/gekko/gekko/node_modules/tulind
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.9/Release/tulind-v0.8.9-node-v48-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for tulind@0.8.9 and node@6.12.2 (node-v48 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory `/home/gekko/gekko/node_modules/tulind/build'
  CXX(target) Release/obj.target/tulind/tulind.o
In file included from ../tulind.cpp:25:
../node_modules/nan/nan.h:47:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /home/gekko/.node-gyp/6.12.2/include/node/node.h:42,
                 from ../node_modules/nan/nan.h:51,
                 from ../tulind.cpp:25:
/home/gekko/.node-gyp/6.12.2/include/node/v8.h:345: error: expected unqualified-id before ‘using’
/home/gekko/.node-gyp/6.12.2/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/home/gekko/.node-gyp/6.12.2/include/node/v8.h:362: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.2/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/home/gekko/.node-gyp/6.12.2/include/node/v8.h:369: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.2/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/home/gekko/.node-gyp/6.12.2/include/node/v8.h:373: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.2/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/home/gekko/.node-gyp/6.12.2/include/node/v8.h:441: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.2/include/node/v8.h: At global scope:
/home/gekko/.node-gyp/6.12.2/include/node/v8.h:481: error: expected unqualified-id before ‘using’
/home/gekko/.node-gyp/6.12.2/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/home/gekko/.node-gyp/6.12.2/include/node/v8.h:820: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.2/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/home/gekko/.node-gyp/6.12.2/include/node/v8.h:845: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.2/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/home/gekko/.node-gyp/6.12.2/include/node/v8.h:857: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.2/include/node/v8.h: At global scope:
/home/gekko/.node-gyp/6.12.2/include/node/v8.h:882: error: expected unqualified-id before ‘using’
/home/gekko/.node-gyp/6.12.2/include/node/v8.h:1119: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.2/include/node/v8.h:1125: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.2/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/home/gekko/.node-gyp/6.12.2/include/node/v8.h:3279: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.2/include/node/v8.h: At global scope:
/home/gekko/.node-gyp/6.12.2/include/node/v8.h:4499: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.2/include/node/v8.h:4515: error: ‘nullptr’ was not declared in this scope
/home/gekko/.node-gyp/6.12.2/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/home/gekko/.node-gyp/6.12.2/include/node/v8.h:7544: error: ‘nullptr’ was not declared in this scope
In file included from ../node_modules/nan/nan.h:197,
                 from ../tulind.cpp:25:
../node_modules/nan/nan_maybe_43_inl.h: At global scope:
../node_modules/nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’
../node_modules/nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before ‘using’
../node_modules/nan/nan_maybe_43_inl.h:19: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:24: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:29: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:37: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:45: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:52: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:60: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:71: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:79: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:87: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:96: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:105: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:116: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:133: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:143: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:159: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:167: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:173: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:182: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:189: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:197: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:204: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:212: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:220: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:228: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:236: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:244: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:252: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:262: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:272: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:284: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:295: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:302: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:308: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:314: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:320: error: expected initializer before ‘<’ token
../tulind.cpp:316: error: expected ‘}’ at end of input
../node_modules/nan/nan_callbacks_12_inl.h:167: warning: ‘void Nan::imp::FunctionCallbackWrapper(const v8::FunctionCallbackInfo<v8::Value>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:181: warning: ‘void Nan::imp::GetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:197: warning: ‘void Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:253: warning: ‘void Nan::imp::PropertyGetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:270: warning: ‘void Nan::imp::PropertySetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:290: warning: ‘void Nan::imp::PropertyEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:306: warning: ‘void Nan::imp::PropertyDeleterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:323: warning: ‘void Nan::imp::PropertyQueryCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:428: warning: ‘void Nan::imp::IndexGetterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:444: warning: ‘void Nan::imp::IndexSetterCallbackWrapper(uint32_t, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:464: warning: ‘void Nan::imp::IndexEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:480: warning: ‘void Nan::imp::IndexDeleterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:496: warning: ‘void Nan::imp::IndexQueryCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
make: *** [Release/obj.target/tulind/tulind.o] 오류 1
make: Leaving directory `/home/gekko/gekko/node_modules/tulind/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 2.6.32-696.16.1.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/gekko/gekko/node_modules/tulind/lib/binding/Release/node-v48-linux-x64/tulind.node" "--module_name=tulind" "--module_path=/home/gekko/gekko/node_modules/tulind/lib/binding/Release/node-v48-linux-x64"
gyp ERR! cwd /home/gekko/gekko/node_modules/tulind
gyp ERR! node -v v6.12.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/gekko/gekko/node_modules/tulind/lib/binding/Release/node-v48-linux-x64/tulind.node --module_name=tulind --module_path=/home/gekko/gekko/node_modules/tulind/lib/binding/Release/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/gekko/gekko/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Linux 2.6.32-696.16.1.el6.x86_64
node-pre-gyp ERR! command "/usr/bin/node" "/home/gekko/gekko/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/gekko/gekko/node_modules/tulind
node-pre-gyp ERR! node -v v6.12.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/gekko/gekko/node_modules/tulind/lib/binding/Release/node-v48-linux-x64/tulind.node --module_name=tulind --module_path=/home/gekko/gekko/node_modules/tulind/lib/binding/Release/node-v48-linux-x64' (1)
npm ERR! Linux 2.6.32-696.16.1.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "tulind"
npm ERR! node v6.12.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! tulind@0.8.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tulind@0.8.9 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tulind package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tulind
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tulind
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gekko/gekko/npm-debug.log

**Comment by codeplea** [comment]
I think this is the relevant line:

>error: #error This version of node/NAN/v8 requires a C++11 compiler

Try installing a newer compiler and try again.

**Comment by gerosyab** [comment]
Finally I re-installed centos 7.4 and update my development enviroment (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)).
Problem solved.
Thanks.
