### ISSUE TITLE
Not working ubuntu 16.04

### ISSUE THREAD

**Issue by tosolini** [TulipCharts/tulipnode#17]
npm install tulind report:

```
node-pre-gyp ERR! Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.7/Release/tulind-v0.8.7-node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for tulind@0.8.7 and node@8.9.2 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
```

**Comment by Deathnerd** [comment]
Getting the same error. Tulipnd is a dependency of Gekko, which is failing on the 0.8.7 build. Running on the default NodeJS Ubuntu 16.04 x64 build on Digital Ocean if that helps

**Comment by codeplea** [comment]
Those errors are normal, and it should fall-back to building from source. Please try again with a fresh install and report back how it works. If there are errors, please attach the full log.

**Comment by DannielPoernomo** [comment]
it works when force building from source
npm install tulind --build-from-source

**Comment by codeplea** [comment]
It looks like those are just warnings. I'll look into fixing them, but it shouldn't be a big deal if that's the only issue you're seeing.

**Comment by Deathnerd** [comment]
Turns out I didn't have `build-essential` installed on my distribution and `node-gyp` was choking on `make`. I had originally not considered that because I could've swore my setup script installed `build-essential`. Oh well. Yeah, that one's on me :/
