### ISSUE TITLE
provide windows precompiled binaries (node-pre-gyp)

### ISSUE THREAD

**Issue by askmike** [TulipCharts/tulipnode#2]
Hey,

First of all thanks for the great project! [A tool](https://github.com/askmike/gekko) I am building uses TA indicators. I am currently using [talib](https://www.npmjs.com/package/talib) for this (though this isn't a hard dependency, as Windows users can't currently install it).

I was hoping to switch to tulipnode instead. Is this in anyway possible / hard to do?

**Comment by codeplea** [comment]
Hi, thanks for reaching out!

I'm glad to hear that you're considering tulipnode for your project.

Currently, tulipnode complies very well on Windows, provided you have npm and a C++ compiler setup.

I understand a lot of node.js developers may not want the hassle of dealing with a C++ compiler, so I agree that pre-compiled binaries may be the way to go. I'm not familiar with node-pre-gyp, but it looks like a good solution. I'll look into it and get back to you. Hopefully we'll have something going soon.

**Comment by codeplea** [comment]
Okay, so this was a configuration nightmare, but I think I have it going.

If you run `npm install tulind` on Windows, there's a good chance you'll see:

> [tulind] Success: "C:\...\tulind.node" is installed via remote

The `installed via remote` part meaning that it worked. If it can't find a binary for your platform, it'll just try to compile it instead.

Can you give it a try and let me know what happens?

**Comment by askmike** [comment]
Thanks for the quick fix, appears to work great!

![screen shot 2017-04-21 at 11 35 05](https://cloud.githubusercontent.com/assets/969743/25274218/f1defee0-2686-11e7-9131-5449f43840ba.png)

I'll work on integrating tulind into Gekko.
