### ISSUE TITLE
Invalid number of options error

### ISSUE THREAD

**Issue by timothyerwin** [TulipCharts/tulipnode#23]
I'm getting this error when trying to use the Awesome Oscillator which has 0 options:

https://github.com/TulipCharts/tulipnode/blob/master/tulind.cpp#L135

```javascript
     return await tulind.indicators.ao.indicator([high, low], []);
```

`Invalid number of options`

If I don't pass the options array I get

```javascript
     return await tulind.indicators.ao.indicator([high, low]);
```

`Expecting third argument to be array of options.`

It also doesn't appear to work on the demo page:

https://tulipindicators.org/ao

**Comment by codeplea** [comment]
It should work with your first code.

I just tried this and it works:

```
> var k = require('tulind');
> var l = [5,5,6,5,8,4,58,6,5,8,4,5,8,5,6,5,8,4,5,6,5,8,5,4,5,8,5,8,5,85,6,5,6,5,6,5];
> k.indicators.ao.indicator([l,l], []);
Promise {
  [ [ 11.811764705882355, -4.0176470588235285, -4.217647058823529 ] ] }

```

Either double check your code, or post a complete, but minimal, example.

The reason it doesn't work on the demo page is that I used the same data for each indicator, and I simply didn't include enough bars to get tho AO going (it uses a 34 period average!).
