### ISSUE TITLE
Can you please add vortex oscillator?

### ISSUE THREAD

**Issue by sacharbit** [TulipCharts/tulipnode#24]
Hi everyone,

I'm very interested by your project but I just need the vortex oscillator.

You can find a file where someone actually used it but there's no documentation and I have a bit of difficulty understanding it and it's [here](https://github.com/horaclito/technical-indicators/blob/master/vtx.src.js).

Please, can you implement it?

Sincerely,
Sacha.

**Comment by codeplea** [comment]
TulipNode is just a wrapper of [TulipIndicators](https://github.com/TulipCharts/tulipindicators). You should repost your request over there.
