### ISSUE TITLE
Stochastic Oscillator Spelling Error

### ISSUE THREAD

**Issue by werkkrew** [TulipCharts/tulipnode#25]
In the results of the stochastic oscillator the object result is:

{ sotchK: 92.29885746244832, stochD: 74.30600425658106 }

note, it should be stochK and not sotchK

**Comment by codeplea** [comment]
I'm guessing you're using Gekko? They had this problem with their wrapper, but it has been fixed:

https://github.com/askmike/gekko/commit/f45266ec1859e953dc3def959f80146dddeaf2c9
