### ISSUE TITLE
Problem installing through NPM

### ISSUE THREAD

**Issue by Ed-zo** [TulipCharts/tulipnode#26]
I have tried installing tulip for NodeJS with NPM, but it outputs some errors. First error is
`node-pre-gyp ERR! Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.9/Release/tulind-v0.8.9-node-v57-linux-x64.tar.gz`
but it seem it can't find the file. It shows 0 downloads in the last day so I assume i am not the only one having the troubles. Thank you in advance. The fallback to source compiling did not work either.

**Comment by codeplea** [comment]
It looks like you're on linux, so that error is fine, I don't publish linux binaries. It should fall back to building from source.

**Comment by codeplea** [comment]
Just in case anyone else is having similar problems, could you share how you got it resolved?

**Comment by Ed-zo** [comment]
It was outputting an error 
> gyp ERR! stack Error: not found: make

so I have found I need to install "build-essentials" package for the system. More here: [stackoverflow](https://stackoverflow.com/questions/14772508/npm-failed-to-install-time-with-make-not-found-error). It was a problem on my side. Sorry for bothering you.

**Comment by codeplea** [comment]
Good to know! Thanks for the update.
