### ISSUE TITLE
TypeError when using macd indicator

### ISSUE THREAD

**Issue by firetiger77** [TulipCharts/tulipnode#27]
When using the  macd indicator as follows:
        tulind.indicators.macd.indicator([test], [3, 2, 3], function(err, results) {
            console.log("Result of macd calc is:");
            console.log(results[0]);    //macd
            console.log(results[1]);    //macd_signal
        });

I get the following error:
TypeError: Cannot read property '0' of null

I believe I am using it correctly as I can successfully get other indicators such as the EMA. i.e.: The following works fine:

        tulind.indicators.sma.indicator([BTC_USD_bid], [3], function(err, results) {
            console.log("Result of sma is:");
            console.log(results[0]);
        });

**Comment by codeplea** [comment]
You should always check `err` first! That's what it's there for!

Here, try this instead:

```js
tulind.indicators.macd.indicator([test], [3, 2, 3], function(err, results) {
  if (err) {
    console.log(err); //<--- Prints "Invalid Options"
  } else {
    console.log("Result of macd calc is:");
    console.log(results[0]); //macd
    console.log(results[1]); //macd_signal
  }
});

```

In this case, your options `[3, 2, 3]` don't make sense for MACD. See https://tulipindicators.org/macd
