### ISSUE TITLE
Fail to Install tulind on ec2

### ISSUE THREAD

**Issue by h4xon** [TulipCharts/tulipnode#31]
Hi, I tried to install tulind on amazon ec2 by using PUTTY, but it keeps showing error :
https://i.imgur.com/Ozq65ti.jpg
And I also tried diffrent versions of node js, but the results are still the same.
attached is the error log.
[2018-02-04T03_11_34_437Z-debug.log](https://github.com/TulipCharts/tulipnode/files/1692697/2018-02-04T03_11_34_437Z-debug.log)

**Comment by h4xon** [comment]
I figured it out... , it needs a c++ environment but when I use sudo yum install build-essential to install the kit it always fail. So I find another way to do it :

sudo yum groupinstall "Development Tools"

then npm install tulind finally worked out!

**Comment by codeplea** [comment]
Glad you got it working!
