### ISSUE TITLE
404 tulind-v0.8.9-node-v59-linux-x64.tar.gz 

### ISSUE THREAD

**Issue by superhero** [TulipCharts/tulipnode#32]
```
node-pre-gyp ERR! Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.9/Release/tulind-v0.8.9-node-v59-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for tulind@0.8.9 and node@9.1.0 (node-v59 ABI, glibc) (falling back to source compile with node-gyp)
```

Installation still went through

**Comment by codeplea** [comment]
That's normal. Pre-built binaries are currently only available for Windows. On other platforms it falls back to building from source.

**Comment by superhero** [comment]
I see :) I would suggest that a message in the process declaring that it's expected could help with someone else confused on the matter. But maybe there was in some seance, I don't have the complete log anymore :)
