### ISSUE TITLE
How to calculate in a synchronous way

### ISSUE THREAD

**Issue by MingliangLu** [TulipCharts/tulipnode#38]
Asynchronous calculations are too troublesome

**Comment by codeplea** [comment]
What are you talking about?

**Comment by MingliangLu** [comment]
eg: Calculating EMA in a blocking way.
The program continues to execute the program when the calculation is completed instead of invoking a callback function

**Comment by codeplea** [comment]
Try `await`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

`const result = await tulind.indicators.ema.indicator([close], [9]);`

**Comment by MingliangLu** [comment]
SyntaxError: await is only valid in async function

**Comment by codeplea** [comment]
Did you look at the link from my last comment?
