### ISSUE TITLE
Help needed to bring result ouside of the tulind function

### ISSUE THREAD

**Issue by LooOOooM** [TulipCharts/tulipnode#45]
Hello, for the following example I dont understand how I could bringt the results outside of the tulind function to access the results globaly. I would be very happy if someone could help me here with a working example, as I am very noop to nodeJS

Your example:
```
tulind.indicators.sma.indicator([close], [3], function(err, results) {
  console.log("Result of sma is:");
  console.log(results[0]);
});
```
However I would like to see something like this:
```
var results_outside_of_the_function = tulind.indicators.sma.indicator([close], [3], function(err, results) {
  console.log("Result of sma is:");
  console.log(results[0]);
  return results[0] 
});
console.log(results_outside_of_the_function )
```

How can I access the results in the most upper layer of the program?

**Comment by codeplea** [comment]
Read up on the `await` operator here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

You'll need to wrap your main function in an `async` function: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

The you can do it like this:
```js
const results = await tulind.indicators.sma.indicator([close], [3]);
```

**Comment by LooOOooM** [comment]
thx!! this can get closed
