### ISSUE TITLE
TypeError: Expecting first argument to be function index number.

### ISSUE THREAD

**Issue by Sicria** [TulipCharts/tulipnode#51]
Deleting the index is deleting the reference which is throwing an error.

https://github.com/TulipCharts/tulipnode/blob/master/index.js#L36
Does that need to be deleted?

Running in a test environment and sometimes it passes and sometimes it fails without making any changes.

**Comment by codeplea** [comment]
I don't understand why that line of code would cause a problem.

Can you provide a minimal example that causes the crash? Even if it has to loop or use random data, it would be helpful.

**Comment by Sicria** [comment]
Here's an example. I use the first function to process data and return results, and the second function is a util used by the others to run the indicator in an easier way.

```
async function commodityChannelIndex(data, { period }) {
  // Calculate the indicator results & start offset
  const { start, results } = await runTulipIndicator('cci', data, ['high', 'low', 'close'], [period]);

  // Format the result for the return payload
  return map(data, (tick, index) => ({
    ...tick,
    result: {
      cci: get(results, `[0][${index - start}]`, null),
    },
  }));
}
```

```
async function runTulipIndicator(name, data, dataPoints, config) {
  // Ensure the indicator is correct
  if (!has(tulind.indicators, name)) throw Error('Invalid Indicator');

  // Format all of the values to ensure they're valid
  const options = map(config, toFinite);

  // Calculate result offset
  const start = invoke(tulind.indicators, `${name}.start`, options);

  // Calculate the results
  const results = await invoke(
    tulind.indicators,
    `${name}.indicator`,
    !dataPoints ? [data] : map(dataPoints, x => map(data, x)),
    options,
  );

  return { start, results };
}
```

The weird thing is that if I run a test suite of 5 different indicators testing basic functionality, sometimes they all pass, sometimes they all fail, other times only some pass and others fail.

I've attempted commenting out the line where it deletes the index and that seems to fix this problem. What is the reasoning behind deleting this? What does it do by deleting it?

Let me know if you need any other examples or info.

**Comment by codeplea** [comment]
>What does it do by deleting it?

I think it's being deleted just to keep the public interface a bit more tidy.

>Let me know if you need any other examples or info.

It would be great if you could post a complete, but minimal example. i.e. something I can copy/paste into a new file, run it, and see the error reproduced.

**Comment by Sicria** [comment]
Here's a minimal test case which I can't seem to get consistent results without having to comment out the ``delete`` line.

```
import { expect } from 'chai';
import tulind from 'tulind';
import { map, get } from 'lodash';

async function commodityChannelIndex(data, { period }) {
  // Calculate the indicator results & start offset
  const results = await tulind.indicators.cci.indicator(map(['high', 'low', 'close'], x => map(data, x)), [period]);
  const start = await tulind.indicators.cci.start([period]);

  // Format the result for the return payload
  return map(data, (tick, index) => ({
    result: get(results, `[0][${index - start}]`, null),
  }));
}

const PRICES = [
  { high: 86, low: 1, close: 81, expectedResult: null },
  { high: 85, low: 5, close: 24, expectedResult: null },
  { high: 90, low: 14, close: 75, expectedResult: null },
  { high: 95, low: 10, close: 21, expectedResult: null },
  { high: 58, low: 20, close: 34, expectedResult: null },
  { high: 71, low: 10, close: 25, expectedResult: null },
  { high: 84, low: 1, close: 72, expectedResult: null },
  { high: 98, low: 48, close: 92, expectedResult: null },
  { high: 99, low: 64, close: 99, expectedResult: 96.66666666666667 },
  { high: 100, low: 0, close: 2, expectedResult: -76.83982683982684 },
];

describe('Commodity Channel Index (CCI)', () => {
  it('should correctly calculate CCI with period 5', async () => {
    const results = await commodityChannelIndex(PRICES, { period: 5 });
    results.forEach((item, index) => {
      expect(item.result).to.equal(get(PRICES, `[${index}].expectedResult`));
    });
  });
});
```

**Comment by codeplea** [comment]
I can't reproduce the problem. I've run your code and it passes. I added in a loop to make it run 10,000 times, and it still works. I also don't understand why (theoretically) the `delete ind.index` would cause the problem you're describing.

We must be missing something.

Please either create a minimal/complete example that causes the crash on a fresh OS with a fresh version of node installed (ideally without requiring mocha or any other dependencies), or help me understand why the `delete ind.index` would theoretically cause what you're describing.

**Comment by Sicria** [comment]
I believe this may only occur in testing environments as I've had no problems in dev/prod when actually using this package. The problem only arises when tests are being run. I'm not sure what actually causes this issue.

As for the ``delete ind.index`` I'm not sure about the benefit of keeping the interface clean by 1 field if it can potentially cause issues in testing environments.

**Comment by codeplea** [comment]
>As for the delete ind.index I'm not sure about the benefit of keeping the interface clean by 1 field if it can potentially cause issues in testing environments.

What you're advocating is for is [Programming by Coincidence](https://pragprog.com/the-pragmatic-programmer/extracts/coincidence). I'm not going to change the code unless I understand the change. I'm certainly not going to modify the public interface in doing so.

I do have a theory now about what is happening. I think that `index.js` is being run multiple times in your environment. The first time it works fine, but the second time it fails because `ind.index` has already been deleted.

Can you put a `console.log("IN TULIND INDEX.JS")` statement at the top of `index.js`? Run your tests and let me know if it logs more than once.

**Comment by Sicria** [comment]
I've added console logs into the code at different points.

Each time a test is run they are logged, it looks like the first succeeds and the following fail.

Console logs are at two different points, the one you requested on line 5 just under the requires, and another on line 26 ``console.log(ind, index);`` inside the ``make_start`` call.

This is the first test to be run.
```
console.log node_modules/tulind/index.js:5
      IN TULIND INDEX.JS
    console.log node_modules/tulind/index.js:26
      { name: 'rsi',
        full_name: 'Relative Strength Index',
        type: 'indicator',
        inputs: 1,
        options: 1,
        outputs: 1,
        input_names: [ 'real' ],
        option_names: [ 'period' ],
        output_names: [ 'rsi' ],
        indicator: [Function],
        start: [Function] } 69
```

This is a test which is run after, there's other tests which report the same things.
```
console.log node_modules/tulind/index.js:5
      IN TULIND INDEX.JS
    console.log node_modules/tulind/index.js:26
      { name: 'sma',
        full_name: 'Simple Moving Average',
        type: 'overlay',
        inputs: 1,
        options: 1,
        outputs: 1,
        input_names: [ 'real' ],
        option_names: [ 'period' ],
        output_names: [ 'sma' ],
        indicator: [Function],
        start: [Function] } undefined
```

**Comment by codeplea** [comment]
Ok, so your test environment is loading `index.js` multiple times. It is not, however, loading the C++ code multiple times. So the second time `index.js` is run, it's getting an already-modified object from the C++ code.

This seems like a bug in your testing environment (mocha?). If the test suite is going to load `index.js` again, it should load the C++ code again too.

The reason this doesn't cause a problem in production is because `require()` and `import` only load code once, even if they are called many times.

I guess the "fix" would be to detect if the processing has already happened in `index.js` and just skip to the end.

Try adding this line of code in the for loop right after `var ind = indicators[key];`:

`if (typeof ind.indicator == 'function') break;`

Keep the `delete ind.index;` line. Please let me know if that fixes it.

**Comment by Sicria** [comment]
Nice work @codeplea that did the trick!

**Comment by codeplea** [comment]
Ok, I'm able to reproduce your error with this:

```

var close = [4,5,6,6,6,5,5,5,6,4];
var tulind;


tulind = require('tulind');

tulind.indicators.sma.indicator([close], [3], function(err, results) {
  console.log("Result of sma is:");
  console.log(results[0]);
});


delete require.cache[require.resolve('tulind')];
tulind = require('tulind');

tulind.indicators.sma.indicator([close], [3], function(err, results) {
  console.log("Result of sma is:");
  console.log(results[0]);
});
```

I'll work on getting an update out tomorrow.

Thanks for working with me on this.

**Comment by Sicria** [comment]
Really appreciate you taking the time to look into it.

**Comment by codeplea** [comment]
It's published.
