### ISSUE TITLE
Callback function not working NodeJS

### ISSUE THREAD

**Issue by collector90** [TulipCharts/tulipnode#53]
I'm having trouble writing the callback functions for indicators with more than 3 arguments. An example called function that causes the error is: 

`  
MoneyFlowIndex: function(high, low, close, volume, period) {
    let result;
    tulind.indicators.mfi.indicator([high], [low], [close], [volume], [period], function(err, results) {
      result = results[0];
    })
    return result;
  },
`

It then returns `TypeError: Expecting last argument to be callback function.`
The error message originates from source code at index.js:17:21. 

Might be a rookie question from my part, but would love to get some help :)

**Comment by codeplea** [comment]
Each indicator takes three arguments: the inputs, the options, the callback. Try this:

`tulind.indicators.mfi.indicator([high, low, close, volume], [period], function(err, results) {...});`

**Comment by collector90** [comment]
Alright that worked. Seemed my main issue was that I didn't declare the [options] field (for Indicators that have no options). If I fill in an empty field for the options ( [ ] ) all is well.
