### ISSUE TITLE
Unable to install tulind

### ISSUE THREAD

**Issue by rubjhavar** [TulipCharts/tulipnode#54]
Hi, I was trying to install tulind on my windows but unable to proceed. I even tried installing
node-pre-gyp install --fallback-to-build

but no luck . Please suggest.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tulind@0.8.15 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tulind@0.8.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rubal\AppData\Roaming\npm-cache\_logs\2019-06-23T05_42_51_947Z-debug.log

**Comment by codeplea** [comment]
What version of node are you using?

You should install with `npm install tulind`.

**Comment by prenesh0309** [comment]
iam unable to install with latest node version.

**Comment by codeplea** [comment]
Do you have Python installed?

**Comment by prenesh0309** [comment]
> Do you have Python installed?

yes i had 3.8 . I installed 3.7 in the path mentioned in the error messages and then it worked. had to install c++ stuffs as well with visual studio. got it running now. 

Thanks.

**Comment by codeplea** [comment]
I'm glad its working.
