### ISSUE TITLE
Stochrsi %k and %d?

### ISSUE THREAD

**Issue by c0nf1ck** [TulipCharts/tulipnode#64]
How can I calculate the value of %K and %D in stochrsi using this library?

Thanks

**Comment by codeplea** [comment]
Sounds like you want stoch, not stochrsi.

**Comment by c0nf1ck** [comment]
Hey @codeplea, no I want stochrsi just like trading view. As u can see:

![Screenshot_20191123-151405__01](https://user-images.githubusercontent.com/34660211/69483282-af773900-0dfb-11ea-947e-63da8f44ccbf.jpg)
 
There's a way to calculate using this library?

**Comment by codeplea** [comment]
Ah, what trading view does isn't really stochrsi. It's just stoch run over rsi. You can calculate it by running rsi first, then running stoch on that output (using rsi output as the high, low, and close inputs to stoch).

Tulip Indicators will probably offer this as a built-in function in the future, but for now it takes these two passes. See here for more info: https://github.com/TulipCharts/tulipindicators/issues/23

**Comment by c0nf1ck** [comment]
Ohh ok. That's ok then

Thanks @codeplea
