### ISSUE TITLE
Crossover

### ISSUE THREAD

**Issue by mahmutoktay** [TulipCharts/tulipnode#68]
How to set the crossover.  for example sma50 crossover sma200

**Comment by codeplea** [comment]
https://tulipindicators.org/sma
https://tulipindicators.org/crossover

**Comment by mahmutoktay** [comment]
Thank you for your interest. 

` let sma50 = [59992.435, 59986.2692,59971.1268, 59957.55, 59939.7342, 59923.3578, 59913.519,59909.878,59908.490, 
        59909.5954,59930.5108, 59934.7724,59941.2926, 59948.0484]; 

       let sma200 = [59992.4359,59986.2692,59971.1268, 59957.5554,59939.7342, 59923.3578000, 
            59913.519799999995, 59909.878,59908.490200,  59909.595400,  59911.643400, 59914.5622000,
            59917.27980, 59918.138200];

        await tulind.indicators.crossover.indicator([sma50,sma200],(err,res)=>{

            if(err) return log(err);
        
            console.log(res);

        }); `

where am i making a mistake

`UnhandledPromiseRejectionWarning: TypeError: Expecting third argument to be array of options.`

**Comment by ergisgjergji** [comment]
@mahmutoktay @codeplea About time to close this issue, I think?
