### ISSUE TITLE
Passing values from 1m candles breaks ADX

### ISSUE THREAD

**Issue by thegamecat** [TulipCharts/tulipnode#8]
If I pass the high, low, close arrays populated by 1m candles ADX / results returns NaN. If I pass 2m candles it works.

Any idea why? I'm assuming there is something in the dataset...I could share that if it helps.

**Comment by codeplea** [comment]
Tulipnode has no notion of data frequency. You simply pass it an array, and it produces another array. It does not know or care what time interval that those arrays represent.

If you think this is a problem with Tulipnode, please post a minimal but complete example I can run.
