### ISSUE TITLE
ADX return array limited by the length of the array/input passed to it

### ISSUE THREAD

**Issue by thegamecat** [TulipCharts/tulipnode#9]
Inside the application that builds the array/input the max size of the array is defaulted to 1000 and is mainted by a push/shift() function. This doesn't seem to work with Tulip. Is there any way to make Tulip work with a different data set  / input per cycle?

**Comment by codeplea** [comment]
Where are you seeing a default array size in Tulipnode? What push/shift function are you talking about?

**Comment by thegamecat** [comment]
This is really what I was getting at here: https://github.com/TulipCharts/tulipnode/issues/7
